### ISSUE TITLE
Создание тестового приложения

### ISSUE THREAD

**Issue by vddnngu** [vddnngu/morkovka#2]
- Необходимо создать тестовое приложение, для проверки корректности работы классов Link и TestProcessing.

 

- Суть приложения: перед пользователем возникает графическое окно с 3 текстовыми полями, 2 первых неизменяемы, и еще одно изменяется пользователем.

-  В первом поле выводиться вопрос, во втором варианты ответа, в третье поле пользователь вводит свой ответ. Далее нажимает на кнопку ввод. После этого первые 2 поля меняют свое содержимое (в зависимости от выбранного ответа) на сл. вопрос(или на ответ) и соответствующие ему ответы.

задача закреплена за Катауровой Анастасией @Kataurovaa  срок выполнения задачи, до 28.10.2019

**Comment by Kataurovaa** [comment]
**Задача выполнена.** 

- Создана ветка TestCase3010 для выполнения поставленной задачи
- Протестирован функционал класса TestProcessing 
- Обнаружена ошибка: в классе TestProcessing отсутствует метод для получения текущего Link'а
- Данная ошибка имеет максимальный приоритет, так как не имея возможности доступа к текущему Link'у, мы не имеем возможности вывести текст текущего вопроса
  Просьба провести ревью данной задачи @vddnngu

**Comment by vddnngu** [comment]
Настя, молодец!
