### ISSUE TITLE
Исправление ошибки выявленной в ходе тестирования

### ISSUE THREAD

**Issue by vddnngu** [vddnngu/morkovka#3]
В ходе тестирования (ветка TestCase3010) была обнаружена ошибка: Недостаточность функционала класса TestProcessing

**Суть проблемы:** В классе TestProcessing  отсутствует метод дающий возможность получить доступ к текущему линку.

**Приоритет:** максимальный

**Задача:** Исправить найденную проблему путем добавления отсутствующего функционала

задача закреплена за Катауровой Анастасией @Kataurovaa  срок выполнения задачи 6.11.2019

**Comment by Kataurovaa** [comment]
**Задача выполнена**

- В классе TestProcessing добавлен новый метод getCurQuestion(), возвращающий текст текущего вопроса
- Были добавлены новые вопросы для более качественной проверки созданного метода

Просьба провести ревью данной задачи @vddnngu

**Comment by vddnngu** [comment]
**Задача проверена**
Есть некоторые замечания

- Посмотри комментарии в ветке

- Создай отдельную ветку, в которой будут только изменения TestProcessing, без тестовой и отадочной части

Настя @Kataurovaa исправляй

**Comment by Kataurovaa** [comment]
**Исправлены ошибки**

- Создана новая ветка, на которой в классе TestProcessing реализованы методы getCurLinkText для получения текста текущего линка и getCurLinkType для получения типа текущего линка

Прошу проверить исправления @vddnngu

**Comment by vddnngu** [comment]
**Задача проверена**

- задача выполнена

- Ветка HomeWork слита с мастером
